// Generated by CoffeeScript 1.6.1
(function() {
  var foo, hello;

  hello = function() {
    return console.log('hello from utils...');
  };

  foo = function() {
    return console.log('foo from utils...');
  };

  module.exports = {
    hello: hello,
    allCows: [
      {
        'name': 'Dagros'
      }, {
        'name': 'Rosa'
      }
    ]
  };

}).call(this);
